services:
  - type: web
	name: echotag
	env: python
	plan: free
	buildCommand: "pip install -r requirements.txt"
	startCommand: "gunicorn backend.app:app"
	envVars:
	  - key: FLASK_ENV
		value: production